apiVersion: bdc.kdp.io/v1alpha1
kind: Application
metadata:
  labels:
    app: mysql
    app.core.bdos/type: system
  annotations:
    app.core.bdos/catalog: mysql
    app.core.bdos/extra-image: bitnami/mysql:8.0.22,bitnami/mysqld-exporter:0.14.0-debian-11-r93,mysql-toolkit/xtrabackup-ssh:8.0.22,kroniak/ssh-client:3.15
    definition.bdc.kdp.io/description: mysql
spec:
  type: mysql
  properties:
    version: "9.23.0"
    architecture: "standalone"
    resources:
      limits:
        cpu: '2.0'
        memory: "4Gi"
      requests:
        cpu: "0.1"
        memory: "1024Mi"
    persistence:
      enabled: true
      size:    "20Gi"
    mysqlConfig: |-
        [mysqld]
        default_authentication_plugin=mysql_native_password
        skip-name-resolve
        explicit_defaults_for_timestamp
        basedir=/opt/bitnami/mysql
        plugin_dir=/opt/bitnami/mysql/lib/plugin
        port=3306
        socket=/opt/bitnami/mysql/tmp/mysql.sock
        datadir=/bitnami/mysql/data
        tmpdir=/opt/bitnami/mysql/tmp
        max_allowed_packet=16M
        bind-address=0.0.0.0
        pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
        log-error=/opt/bitnami/mysql/logs/mysqld.log
        character-set-server=UTF8
        collation-server=utf8_general_ci
        skip-host-cache
        skip-ssl
        symbolic-links=0
        default-time-zone='+08:00'
        enforce_gtid_consistency=ON
        gtid_mode=ON
        binlog_checksum=NONE
        binlog_row_image=minimal
        expire_logs_days=3
        max_connections=3000
        max_user_connections=1000
        innodb_buffer_pool_size=6442450944
        slow-query-log=1
        slow-query-log-file=/opt/bitnami/mysql/logs/slow-query.log
        long_query_time=10
        log-queries-not-using-indexes
        [client]
        port=3306
        socket=/opt/bitnami/mysql/tmp/mysql.sock
        default-character-set=UTF8
        plugin_dir=/opt/bitnami/mysql/lib/plugin
        [manager]
        port=3306
        socket=/opt/bitnami/mysql/tmp/mysql.sock
        pid-file=/opt/bitnami/mysql/tmp/mysqld.pid