apiVersion: bdc.kdp.io/v1alpha1
kind: Application
metadata:
  annotations:
    app.core.bdos/catalog: flink
    reloader.stakater.com/auto: "true"
    app.core.bdos/extra-image: "streampark:v1.0.0-2.1.2"
  labels:
    app: streampark
    app.core.bdos/type: system
spec:
  name: streampark
  type: streampark
  properties:
    replicas: 1
