blank_issues_enabled: true
contact_links:
  - name: Questions
    about: Please use one of the forums for questions or general discussions
    url:  https://github.com/linktimecloud/kubernetes-data-platform/pulls