# Default values for kdp-infra.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## @section kdp-infra parameters
## @param image.registry Image registry
## @param image.repository Image repository
## @param image.pullPolicy Image pull policy
## @param image.tag Image tag
## @param image.digest Image digest
image:
  registry: "od-registry.linktimecloud.com"
  repository: kdp-infra
  # IfNotPresent Always
  pullPolicy: Always
  tag: ""
  digest: "sha256:80943fb18936e4650fafa399853d19f04d52ccd93307a8e6fef59be6c012b353"

## @param imagePullSecrets Image pull secrets
imagePullSecrets: []
## @param nameOverride String to partially override kdp-infra.fullname
nameOverride: ""
## @param fullnameOverride String to fully override kdp-infra.name
fullnameOverride: ""

## @param serviceAccount.create Create serviceAccount
## @param serviceAccount.automount Automatically mount a ServiceAccount's API credentials?
## @param serviceAccount.annotations Annotations to add to the service account
## @param serviceAccount.name The name of the service account to use.
serviceAccount:
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  annotations: {}
  # If not set and create is true, a name is generated using the fullname template
  name: ""

## @param podAnnotations
podAnnotations: {}
## @param podLabels
podLabels: {}

## @param service.port Service port
service:
  port: "9115"

## @param resources
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

## @param volumes Volumes for the output Deployment definition
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

## @param volumeMounts Volume mounts for the output Deployment definition
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

## @param nodeSelector Node selector for pod assignment
nodeSelector: {}

## @param affinity Affinity for pod assignment
affinity: {}

## @param livenessProbe.initialDelaySeconds Initial delay seconds for the liveness probe
## @param livenessProbe.periodSeconds Period seconds for the liveness probe
## @param livenessProbe.timeoutSeconds Timeout seconds for the liveness probe
## @param livenessProbe.failureThreshold Failure threshold for the liveness probe
## @param livenessProbe.successThreshold Success threshold for the liveness probe
livenessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3
  successThreshold: 1

## @param readinessProbe.initialDelaySeconds Initial delay seconds for the readiness probe
## @param readinessProbe.periodSeconds Period seconds for the readiness probe
## @param readinessProbe.timeoutSeconds Timeout seconds for the readiness probe
## @param readinessProbe.failureThreshold Failure threshold for the readiness probe
## @param readinessProbe.successThreshold Success threshold for the readiness probe
readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3
  successThreshold: 1

## @param metrics.serviceMonitor.enabled Enable the ServiceMonitor resource for Prometheus Operator
## @param metrics.serviceMonitor.additionalLabels Additional labels that can be used so ServiceMonitor will be discovered by Prometheus
## @param metrics.serviceMonitor.interval Specify the interval at which metrics should be scraped
## @param metrics.serviceMonitor.scrapeTimeout Specify the timeout after which the scrape is ended
metrics:
  serviceMonitor:
    enabled: true
    additionalLabels: {}
    interval: 30s
    scrapeTimeout: 30s


