kind: ClusterRole
rules:
  - verbs:
      - '*'
    apiGroups:
      - 'extensions.kubesphere.io'
    resources:
      - '*'
  - apiGroups:
    - 'apiextensions.k8s.io'
    resources:
      - 'customresourcedefinitions'
    verbs:
      - '*'
  - apiGroups:
    - 'rbac.authorization.k8s.io'
    resources:
      - 'clusterroles'
      - 'clusterrolebindings'
    verbs:
      - '*'
  - apiGroups:
      - ''
    resources:
      - 'namespaces'
    verbs:
      - '*'
  - apiGroups:
      - 'installer.kdp.io'
    resources:
      - 'infrastructures'
    verbs:
      - '*'


---
kind: Role
rules:
  - verbs:
      - '*'
    apiGroups:
      - ''
      - 'apps'
      - 'batch'
      - 'app.k8s.io'
      - 'autoscaling'
    resources:
      - '*'
  - verbs:
      - '*'
    apiGroups:
      - 'networking.k8s.io'
    resources:
      - 'ingresses'
      - 'networkpolicies'
