name: CI-Push

on:
  push:
    branches:
      - main
      - release-*
    tags:
      - "v*"
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  publish-core-images:
    permissions:
      packages: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
        with:
          submodules: true

      - name: Build CLI and Push CLI
        run: |
          make kdp-cli-push SERVER_USER=${{ secrets.REG_USER }} SERVER_PASSWORD=${{ secrets.REG_PASSWD }} SERVER_URL= ${{ secrets.ARTIFACT_SERVER_PULL }}

      - name: Docker Login
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          username: ${{ secrets.REG_USER }}
          password: ${{ secrets.REG_PASSWD }}

      - name: Build Images
        id: build
        run: |
          make docker-build IMG_REGISTRY=${{ secrets.CONTAINER_REGISTRY }}

      - name: Push Images
        run: |
          make docker-push IMG_REGISTRY=${{ secrets.CONTAINER_REGISTRY }}